name: Package and Release VS Code Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codegit 
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Install dependencies
      run: npm install

    - name: Package extension
      run: vsce package

    - name: Create Git tag
      run: |
        tag_name=v$(date +'%Y.%m.%d') # Example: v2024.08.18
        git tag $tag_name
        git push origin $tag_name

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.vsix"
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: vsix
        path: '*.vsix'
