name: Package and Release VS Code Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codegit 
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install vsce
      run: |
        npm install -g @vscode/vsce
        npm install
        vsce package

    - name: Tag
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        git tag "v$env:GitVersion_SemVer"
        git push origin "v$env:GitVersion_SemVer"

    - name: Release
      if: startsWith(github.ref, 'refs/heads/release/')
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ env.GitVersion_SemVer }}
        prerelease: ${{ env.GitVersion_PreReleaseLabel != '' }}
        files: ./artifacts/sidekick-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: vsix
        path: '*.vsix'
